part_keepr_auth:
    resource: "@PartKeeprAuthBundle/Controller/"
    type:     annotation
    prefix:   /

PartKeeprImageBundle:
    resource: "@PartKeeprImageBundle/Controller/"
    type:     annotation
    prefix:   /

_frontend:
    resource: "@PartKeeprFrontendBundle/Resources/config/routing.yml"

api:
    resource: "."
    type:     "api"
    prefix:   "/api" # Optional